BroadcastSocialMedia/BroadcastSocialMedia/Controllers/FeaturedController.cs
using BroadcastSocialMedia.Data;
using BroadcastSocialMedia.Models;
using BroadcastSocialMedia.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BroadcastSocialMedia.Controllers
{
    public class FeaturedController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _dbContext;

        public FeaturedController(UserManager<ApplicationUser> userManager, ApplicationDbContext dbContext)
        {
            _userManager = userManager;
            _dbContext = dbContext;

        }
        //Punkt6
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            //Hämtar alla broadcasts sorterat på flest likes
            var broadcasts = await _dbContext.Broadcasts
                    .Include(b => b.User)
                    .Include(b => b.UserThatLike)
                    .OrderByDescending(b => b.UserThatLike.Count)
                    .ToListAsync();


            var viewModel = new FeaturedIndexViewModel()
            {
                SortedBroadcasts = broadcasts,
            };

            return View(viewModel);
        }
    }
}

BroadcastSocialMedia/BroadcastSocialMedia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BroadcastSocialMedia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* Punkt4 *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/BroadcastSocialMedia.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header>
        <nav class="WholeNavbar" @* class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" *@>
            <div id="navbar" class="navbar_style1" @* class="container-fluid" *@>
                <a class="homeLogo navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BROADCAST SOCIAL MEDIA</a>
                @* <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> *@
                <div id="navbarLinksCointainer" class="navbarLinksCointainer_style1" @* class="navbar-collapse collapse d-sm-inline-flex justify-content-between" *@>
                    <ul class="navlist-left" @* class="navbar-nav flex-grow-1" *@>
                        <li @* class="nav-item" *@>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li @* class="nav-item" *@>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">PRIVACY</a>
                        </li>
                        <li @* class="nav-item" *@>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Featured" asp-action="Index">FEATURED</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>

                <button id="switchThemeButton" class="switchThemeButton">SWITCH THEME</button>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
@*             &copy; 2024 - BroadcastSocialMedia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* Punkt4 *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>